### ISSUE TITLE
Color blocking on menu items

### ISSUE THREAD

**Issue by CtrlAltFu** [BurbSec/burbsec.github.io#1]
After selecting a menu item for one of the locations the selected item becomes blocked out and is unable to be read. In the attached screenshot Prime is selected and illegible. 
![IMG_0951](https://github.com/BurbSec/burbsec.github.io/assets/21112270/87e741c5-af9a-43b1-aafe-7a0bb0878414)

**Comment by dieghernan** [comment]
Hi @burbsec

It should be fixed the next time you build the site

**Comment by dieghernan** [comment]
Ping @SteveMcGrath

**Comment by SteveMcGrath** [comment]
@dieghernan Works great in dual
