### ISSUE TITLE
Burbsec Galway Meetup page is not at meetup.com\burbsec

### ISSUE THREAD

**Issue by johnnyxmas** [BurbSec/burbsec.github.io#10]
Because Galway is not in Chicagoland (per most definitions), we don't list them under meetup.com\burbsec in order to remove noise. Galway's meetups are at https://www.meetup.com/burbsec-galway/. Need some way to give the page it's own meetup. I suspect this means it needs a dedicated template.

**Comment by johnnyxmas** [comment]
@SteveMcGrath do you agree?

**Comment by SteveMcGrath** [comment]
Should be simple enough to add.
