### ISSUE TITLE
East and northwest have wrong/missing text

### ISSUE THREAD

**Issue by CtrlAltFu** [BurbSec/burbsec.github.io#4]
![IMG_1029](https://github.com/BurbSec/burbsec.github.io/assets/21112270/5aa718b3-93c8-4dcc-a0ad-c91d31fdffeb)

Highlighted in the attached both East and Northwest name the location with “address below”, with no address below.

**Comment by johnnyxmas** [comment]
Fixed in #5

**Comment by johnnyxmas** [comment]
Fixed in #5
